[General]
__userfile__=true
enableBatteryWatcher=true
enableIdlenessWatcher=true
enableLidWatcher=false
powerLowAction=6
powerLowLevel=5
powerLowWarning=60
runCheckLevel=1
showIcon=true
useThemeIcons=false
