[General]
__userfile__=true
iconTheme=
panels=panel1

[backlight]
alignment=Right
type=backlight

[desktopswitch]
type=desktopswitch

[mainmenu]
alignment=Left
customFont=true
customFontSize=10
icon=/usr/share/icons/manjaro/maia/maia.svg
ownIcon=true
type=mainmenu

[mount]
type=mount

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\"\"++..\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
iconSize=100
lineCount=1
lockPanel=false
opacity=80
panelSize=100
plugins=mainmenu, quicklaunch, taskbar, statusnotifier, backlight, volume, worldclock, tray
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
alignment=Left
apps\1\desktop=/home/nikv/t9launcher/t9launcher.desktop
apps\size=1
type=quicklaunch

[statusnotifier]
alignment=Right
type=statusnotifier

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=Icon
buttonWidth=100
closeOnMiddleClick=true
cycleOnWheelScroll=true
groupingEnabled=true
iconByClass=false
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=false
type=taskbar

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
device=0
type=volume

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=short-timeonly
showDate=false
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=false
