[colors.normal]
black = "#000000"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eaeaea"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[font]
size = 12.0

[font.bold]
family = "RobotoMono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono"
style = "Italic"

[font.normal]
family = "RobotoMono"
style = "Regular"
