theme = "solarized_dark-indent-guides"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.statusline]
center = ["file-type"]

[editor.indent-guides]
render = true
character = "|"

[keys.normal.space."n"]
g = ":sh alacritty -o 'window.startup_mode=\"fullscreen\"' -e gitui"
d = ":sh alacritty -e distrobox enter ursim"
t = ":sh alacritty"

[keys.normal.space."n"."c"]
r = ":sh alacritty -e cargo run"
d = ":sh alacritty -e cargo build --debug"
b = ":sh alacritty -e cargo build --release"
