theme = "solarized_dark-indent-guides"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.statusline]
center = ["file-type"]

[editor.indent-guides]
render = true
character = "|"

[keys.normal.n]
g = ":sh alacritty -e gitui"
